# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := network-tests
ARDUINO_LIBS := AUnit TinyMqtt ESP8266WiFi
ARDUINO_LIB_DIRS := ../../libraries
EPOXY_CORE_PATH := ../../cores/esp8266
include ../../../EpoxyDuino/EpoxyDuino.mk
